CREATE LOGIN AdminUser WITH PASSWORD = 'Admin'
CREATE USER AdminUser FOR LOGIN AdminUser
CREATE ROLE AdminRole 
CREATE ROLE UserRole 
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: dbo TO AdminRole
ALTER ROLE AdminRole ADD MEMBER AdminUser
GRANT SELECT ON SCHEMA :: dbo TO UserRole
ALTER ROLE UserRole ADD MEMBER AdminUser